# Cassandra configuration
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: db
spec:
  serviceName: "cassandra"
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:latest
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: YourCluster
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          ports:
            - containerPort: 9042
              name: cassandra
          volumeMounts:
            - name: cassandra-persistent-storage
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 4Gi

---

apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: db
spec:
  ports:
    - port: 9042
      targetPort: 9042
      nodePort: 30085
  selector:
    app: cassandra
  type: NodePort
