# Postgresql configuration
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-bcs
  namespace: db
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres-bcs
  template:
    metadata:
      labels:
        app: postgres-bcs
    spec:
      containers:
        - image: postgres:latest
          name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgresql-persistent-storage
              mountPath: /var/lib/postgresql
            - name: postgresql-init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgresql-init-script
          configMap:
            name: postgresql-init-script-bcs
  volumeClaimTemplates:
    - metadata:
        name: postgresql-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 4Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-bcs
  namespace: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30083
  selector:
    app: postgres-bcs
  type: NodePort

