apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
  namespace: menstalk
stringData:
  db_username: "postgres"
  db_password: "password"
  jwtSecret: "6MensTalk1Andy2Simon3Roy4Po5Jimmy6BuddySideProject0SplittingBill0"
  jwtExpirationMs: "10800000"