# Jaeger configuration
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: jaeger
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        ports:
        - containerPort: 5775
          name: jaeger-5775
          protocol: UDP
        - containerPort: 6831
          name: jaeger-6831
          protocol: UDP
        - containerPort: 6832
          name: jaeger-6832
          protocol: UDP
        - containerPort: 5778
          name: jaeger-5778
        - containerPort: 16686
          name: jaeger-16686
        - containerPort: 14268
          name: jaeger-14268
        - containerPort: 14250
          name: jaeger-14250
        - containerPort: 9411
          name: jaeger-9411

---

apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: monitoring
spec:
  ports:
    - name: jaeger-agent
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: jaeger-ui
      port: 16686
      targetPort: 16686
      nodePort: 31686
  selector:
    app: jaeger
  type: NodePort