apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: menstalk
data:
  application.yml: |
    server:
      port: 8000
    
    opentracing:
      jaeger:
        enabled: true
        log-spans: false
        const-sampler:
          decision: true
        udp-sender:
          host: jaeger.monitoring
          port: 6831
    
    spring:
      application:
        name: auth-service
      sleuth:
        enabled: false
      datasource:
        url: jdbc:postgresql://postgres-as.db:5432/auth_service?serverTimezone=Asia/Taipei
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      redis:
        database: 0
        host: redis.db
        port: 6379
        jedis:
          pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
        timeout: 0
      kafka:
        bootstrap-servers: kafka.kafka:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          properties:
            retries: 3
    
    management:
      endpoints:
        web:
          exposure:
            include: health,prometheus
            
    jwt:
      variables:
        jwtSecret: ${JWT_SECRET}
        jwtExpirationMs: ${JWT_EXPIRATION_MS}
