apiVersion: v1
kind: ConfigMap
metadata:
  name: bill-query-service-config
  namespace: menstalk
data:
  application.yml: |
    server:
      port: 8400
    
    opentracing:
      jaeger:
        enabled: true
        log-spans: false
        const-sampler:
          decision: true
        udp-sender:
          host: jaeger.monitoring
          port: 6831
    
    spring:
      application:
        name: bill-query-service
      sleuth:
        enabled: false
      datasource:
        url: jdbc:postgresql://postgres-bqs.db:5432/bill_query_service?serverTimezone=Asia/Taipei
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      kafka:
        bootstrap-servers: kafka.kafka:9092
        consumer:
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
          properties:
            spring:
              deserializer:
                key:
                  delegate:
                    class: org.apache.kafka.common.serialization.StringDeserializer
                value:
                  delegate:
                    class: org.springframework.kafka.support.serializer.JsonDeserializer
              json:
                value:
                  default-key-type: java.lang.String
                  default-value-type: java.lang.String
          group-id: bill-query-service
          auto-offset-reset: latest
    
    management:
      endpoints:
        web:
          exposure:
            include: health,prometheus
            
