apiVersion: v1
kind: ConfigMap
metadata:
  name: master-query-service-config
  namespace: menstalk
data:
  application.yml: |
    server:
      port: 8200
    
    opentracing:
      jaeger:
        enabled: true
        log-spans: false
        const-sampler:
          decision: true
        udp-sender:
          host: jaeger.monitoring
          port: 6831
    
    spring:
      application:
        name: master-query-service
      sleuth:
        enabled: false
      datasource:
        url: jdbc:postgresql://postgres-mqs.db:5432/master_query_service?serverTimezone=Asia/Taipei
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: validate
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
      redis:
        database: 0
        host: redis.db
        port: 6379
        jedis:
          pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
        timeout: 0
      kafka:
        bootstrap-servers: kafka.kafka:9092
        consumer:
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
          properties:
            spring:
              deserializer:
                key:
                  delegate:
                    class: org.apache.kafka.common.serialization.StringDeserializer
                value:
                  delegate:
                    class: org.springframework.kafka.support.serializer.JsonDeserializer
              json:
                value:
                  default-key-type: java.lang.String
                  default-value-type: java.lang.String
          group-id: master-query-service
          auto-offset-reset: latest
    
    management:
      endpoints:
        web:
          exposure:
            include: health,prometheus
    
    resilience4j:
      retry:
        instances:
          default:
            maxAttempts: 5
            waitDuration: 1s
            enableExponentialBackoff: true
